### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by HEMANTHKUMARANNAM** [aniketdhole07/two-way-sign-language-translator#5]
Version combatability error

**Comment by HEMANTHKUMARANNAM** [comment]
PS C:\Users\HEMANTH\Desktop\two-way-sign-language-translator> python -u "c:\Users\HEMANTH\Desktop\two-way-sign-language-translator\main.py"
2024-09-01 15:38:04.043547: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-09-01 15:38:04.952000: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "c:\Users\HEMANTH\Desktop\two-way-sign-language-translator\main.py", line 264, in <module>
    classifier = load_model('model.h5')
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HEMANTH\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\saving\saving_api.py", line 194, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HEMANTH\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 133, in load_model_from_hdf5
    model = saving_utils.model_from_config(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HEMANTH\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\legacy\saving\saving_utils.py", line 58, in model_from_config
    batch_input_shape = config["config"].pop("batch_input_shape", None)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: pop expected at most 1 argument, got 2
